"""empty message

Revision ID: 965af79fbde9
Revises: 
Create Date: 2023-09-16 15:14:08.748228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '965af79fbde9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_name', sa.String(length=200), nullable=False),
    sa.Column('image_file', sa.LargeBinary(), nullable=False),
    sa.Column('upload_date', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    # ### end Alembic commands ###
